name : linting-python-code

run-name : ${{ github.actor }} is learning Github Actions

on :
  workflow_dispatch :

  push:
    branches :
      - main
      - develop
  
  pull_request:
    branches :
      - main
      - develop

jobs:
  build :
    runs-on : ubuntu-latest
    steps :
      - name : Checkout
        uses : actions/checkout@v3
      - name: Set up Python 
        uses : actions/setup-python@v4
        with:
          python-version : "3.10"
      - name : Install dependencies
        run : pip install -r requirements.txt

  linting :
    name : Pylint
    runs-on : ubuntu-latest
    steps :
      - name : Install linter
        run : pip install pylint
      - name : Run linter
        run : pylint ./mklearn
